[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lro"
description="A package for decision-making under uncertainty, using data."
readme = "README.md"
license = {text = "Apache 2.0"}
version = "0.0.1"
authors = [
{name = "Irina Wang", email="iywang@princeton.edu"},
{name = "Cole Becker", email="colebecker@princeton.edu"},
{name = "Bart Van Parys", email="vanparys@mit.edu"},
{name = "Bartolomeo Stellato", email="bstellato@princeton.edu"}
]
dependencies = [
    "cvxpy>=1.3.0",
    "torch",
    "scikit-learn",
    "cvxpylayers"
]

[project.optional-dependencies]
dev = ["pytest", "pre-commit", "python-lsp-server[all]",
       "sphinx", "furo", "nbsphinx", "ipython",
       "pandas"]

[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
