name: Documentation

on: [push]

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          python -m pip install --upgrade pip
          pip install ".[dev]"
      - name: Build documentation
        run: |
          cd docs; make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          publish_dir: ./docs/_build/html/
          github_token: ${{ secrets.GITHUB_TOKEN }}
